# Generated by Django 3.2.23 on 2024-01-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='AircraftID',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='Category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='Class',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='Complex',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='EngineType',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='EquipmentType',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='GearType',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='HighPerformance',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='Make',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='Model',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='Pressurized',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='TAA',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='TypeCode',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='Year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='ActualInstrument',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='AircraftID',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='AllLandings',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='Approach1',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='Approach2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='Approach3',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='Approach4',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='Approach5',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='Approach6',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='Checkride',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='CrossCountry',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='CustomFieldNameCounter',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='CustomFieldNameDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='CustomFieldNameDateTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='CustomFieldNameHours',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='CustomFieldNameNumeric',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='CustomFieldNameText',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='CustomFieldNameToggle',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='DayLandingsFullStop',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='DayTakeoffs',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='Distance',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='DualGiven',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='DualReceived',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='FAA6158',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='FlightReview',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='From',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='GroundTraining',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='HobbsEnd',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='HobbsStart',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='Holds',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='IPC',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='InstructorComments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='InstructorName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='NVG',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='NVGOps',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='NVGProficiency',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='Night',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='NightLandingsFullStop',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='NightTakeoffs',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='OffDuty',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='OnDuty',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='PIC',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='Person1',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='Person2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='Person3',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='Person4',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='Person5',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='Person6',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='PilotComments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='Route',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='SIC',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='SimulatedFlight',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='SimulatedInstrument',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='Solo',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='TachEnd',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='TachStart',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='TimeIn',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='TimeOff',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='TimeOn',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='TimeOut',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='To',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='TotalTime',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
